### ISSUE TITLE
Do we have an example to show how cuba manage the data integrity in two data stores

### ISSUE THREAD

**Issue by peidong-hu** [cuba-labs/custom-data-store#1]
Hi,

In Spring, there are ChainedTransactionManager to help maintain the data integrity in case that App needs to maintain two databases data integrity.

What about Cuba? Do we have any feature to support similar thing if I use an external database along with cuba's internal db.

Peidong

**Comment by jreznot** [comment]
Hi,

It would be great if you ask your questions on our forum and not here, since our community does not read all the issues of the samples: https://www.cuba-platform.com/support/
